name: Biome Lint & Format

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js  22
        uses: actions/setup-node@v4
        with:
          node-version:  22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
      
      - name: Run Biome check
        run: pnpm lint
      
      - name: Run Biome format
        run: pnpm format

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: apply biome format"
            git push
          else
            echo "No formatting changes."
          fi